//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParentPortal.ParentDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Placement
    {
        public int PlacementId { get; set; }
        public int StudentPersonalId { get; set; }
        public int SchoolId { get; set; }
        public Nullable<int> PlacementType { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> BehaviorAnalyst { get; set; }
        public Nullable<int> PrimaryNurse { get; set; }
        public Nullable<int> UnitClerk { get; set; }
        public Nullable<int> Class { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> VisitationStatus { get; set; }
        public Nullable<int> Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
